<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Offers Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>5decf6e0-28d8-4b56-9ae8-7d5241b3fde8</testSuiteGuid>
   <testCaseLink>
      <guid>55f6a9bc-23f2-4fee-9e55-cdea569394cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 392 - Regression-Standard-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93510762-b68a-445c-be47-698589064c34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abcca70c-a85b-42ce-b869-a494a221e96b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b9853e6-aa7c-4c98-85b3-c92313d9e7e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 392 - Regression-Standard</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49fa8ab9-38f9-43f7-affa-d5c1ac7411a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbd495f0-d392-4a89-bcee-8f29e6980956</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee375832-706d-427f-bbf1-e026995f455b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 394 - Regression-StandardExpires-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57c9772d-3f9c-4293-b0f0-bc203540577e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15f899c9-d303-4424-96a2-2b8ce7618e00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f35eb530-ebe7-409d-a7dc-fe0027a3dd73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 394 - Regression-StandardExpires</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3e42be3-5f06-4fff-8d54-7aafb2e4e463</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4add695f-f4c3-41db-b56a-d9769084d89f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bababc46-b805-4562-b896-0212f1eac87b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 396 - Regression-StandardCustomRecurring-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c215552c-5bb6-4c73-b8c7-cb04f0ce9f0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb3cc979-322d-4268-aba5-2a9c0d0cc259</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cbbb10a4-5c77-480c-9ccb-62384a012f12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 396 - Regression-StandardCustomRecurring</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feea132b-d530-419b-bb46-c448240e00f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8ff575f-7965-408a-afc7-39ed34572a62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2cf038bf-e3b7-4c52-848c-a8152a90903b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 398 - PrepaidRenew-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a504764-9262-47e2-b23c-46fac507afe5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55ac72e8-724d-4338-ba6d-ee1e73857b6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82e03f45-eb8e-4d26-9559-bcd4b15da0c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 398 - PrepaidRenew</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b02a8926-9a29-4fd4-8034-73deecd0885d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2f64b71-7e5c-4c0f-a4b9-a6895b7fb722</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29d4855f-4234-4fa9-bb1a-7ecc2a9f920f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 400 - PrepaidStop-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92e8937c-edd3-4484-bb8f-9424d61444ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05aef933-22a8-41c0-8cde-cbe6a5233f7d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37e55e9b-1812-4111-a60b-fdcdf34bcc4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 400 - PrepaidStop</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60e613b6-b25a-43a9-a1d3-6165336a6e80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>391773b6-012c-4991-b00b-13a1456f9d8f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
