<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Offer Tests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-21T10:23:25</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>42b2ec11-9251-4d9b-8565-a3411bb2279c</testSuiteGuid>
   <testCaseLink>
      <guid>aa437d5d-47fa-4f99-84e5-dec9e052f217</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Offer ID 392 - Regression-Standard-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93510762-b68a-445c-be47-698589064c34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abcca70c-a85b-42ce-b869-a494a221e96b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d601571-4ced-40b4-b9fb-5000f0c62e9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Offer ID 392 - Regression-Standard</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49fa8ab9-38f9-43f7-affa-d5c1ac7411a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbd495f0-d392-4a89-bcee-8f29e6980956</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f2ddf5a-4fea-4d8b-9e95-2b3e66d61d13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Offer ID 394 - Regression-StandardExpires-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57c9772d-3f9c-4293-b0f0-bc203540577e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15f899c9-d303-4424-96a2-2b8ce7618e00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>353eee18-02b6-47b1-9ec3-78e0cc478d81</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Offer ID 394 - Regression-StandardExpires</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3e42be3-5f06-4fff-8d54-7aafb2e4e463</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4add695f-f4c3-41db-b56a-d9769084d89f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>461a77b9-59a2-4ef1-a895-a3fa2f35d996</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Offer ID 396 - Regression-StandardCustomRecurring-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c215552c-5bb6-4c73-b8c7-cb04f0ce9f0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb3cc979-322d-4268-aba5-2a9c0d0cc259</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f02a3721-8a92-416e-9422-58d89aad05c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Offer ID 396 - Regression-StandardCustomRecurring</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feea132b-d530-419b-bb46-c448240e00f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8ff575f-7965-408a-afc7-39ed34572a62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78819b6d-4ce7-4ae3-b1c2-a14e5347d0f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Offer ID 398 - PrepaidRenew-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a504764-9262-47e2-b23c-46fac507afe5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55ac72e8-724d-4338-ba6d-ee1e73857b6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c3d43dc-220b-4944-bacd-4b3f2194fd39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Offer ID 398 - PrepaidRenew</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b02a8926-9a29-4fd4-8034-73deecd0885d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2f64b71-7e5c-4c0f-a4b9-a6895b7fb722</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
