<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Offers Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-27T10:15:18</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>5decf6e0-28d8-4b56-9ae8-7d5241b3fde8</testSuiteGuid>
   <testCaseLink>
      <guid>55f6a9bc-23f2-4fee-9e55-cdea569394cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 392 - Regression-Standard-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93510762-b68a-445c-be47-698589064c34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abcca70c-a85b-42ce-b869-a494a221e96b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b9853e6-aa7c-4c98-85b3-c92313d9e7e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 392 - Regression-Standard</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c44903c8-d206-4745-97b5-d6ce9ec2180e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da6d12af-54a0-4f6d-9edc-54578fc38c69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee375832-706d-427f-bbf1-e026995f455b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 394 - Regression-StandardExpires-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57c9772d-3f9c-4293-b0f0-bc203540577e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15f899c9-d303-4424-96a2-2b8ce7618e00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f35eb530-ebe7-409d-a7dc-fe0027a3dd73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 394 - Regression-StandardExpires</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3e42be3-5f06-4fff-8d54-7aafb2e4e463</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4add695f-f4c3-41db-b56a-d9769084d89f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bababc46-b805-4562-b896-0212f1eac87b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 396 - Regression-StandardCustomRecurring-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c215552c-5bb6-4c73-b8c7-cb04f0ce9f0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb3cc979-322d-4268-aba5-2a9c0d0cc259</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cbbb10a4-5c77-480c-9ccb-62384a012f12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 396 - Regression-StandardCustomRecurring</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feea132b-d530-419b-bb46-c448240e00f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8ff575f-7965-408a-afc7-39ed34572a62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2cf038bf-e3b7-4c52-848c-a8152a90903b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 398 - PrepaidRenew-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a504764-9262-47e2-b23c-46fac507afe5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55ac72e8-724d-4338-ba6d-ee1e73857b6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82e03f45-eb8e-4d26-9559-bcd4b15da0c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 398 - PrepaidRenew</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b02a8926-9a29-4fd4-8034-73deecd0885d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2f64b71-7e5c-4c0f-a4b9-a6895b7fb722</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29d4855f-4234-4fa9-bb1a-7ecc2a9f920f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 400 - PrepaidStop-Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92e8937c-edd3-4484-bb8f-9424d61444ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05aef933-22a8-41c0-8cde-cbe6a5233f7d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37e55e9b-1812-4111-a60b-fdcdf34bcc4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 400 - PrepaidStop</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60e613b6-b25a-43a9-a1d3-6165336a6e80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>391773b6-012c-4991-b00b-13a1456f9d8f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fffab2b0-9be1-4300-91c1-e6b79bb5031f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 404 - PrepaidCancelRemaining - Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bf9f8e4-9859-4813-912c-103bf0198202</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc6d0f4b-a908-4673-a6f9-fe19497f7016</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac6e2bab-dcba-462f-b885-785c7a607f7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 404 - PrepaidCancelRemaining</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e0fe4ca-f5a8-4b5e-b719-fe0180917bd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d086bc25-6dd6-4d56-9bfd-67875491cff1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6468317-cdca-48a2-b534-00116765b0b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 406 - PrepaidRefundNotAllowed - Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbaad2e5-d2a6-45c4-b5f4-5458cd16be1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5070eec-7cea-4ebe-9db3-07cb4fcb6545</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d227f29c-33de-4261-8767-5d8c3c420f88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 406 - PrepaidRefundNotAllowed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>056a3413-d2dc-4753-8380-e3af5397a2fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db20492a-2c08-43c7-8a2b-3019d9590a0a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1e219c6-847c-498d-a09b-d37d807fb6da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 439 - PrepaidCustomNextRecurring - Trial</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17ae78aa-65fd-4db2-9e9f-76e151b58b87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b27fb19-54d0-4983-8579-ddbe53bc3b5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb823533-4bbe-494d-8ec1-f70bfa472217</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Place Order/Offer ID 439 - PrepaidCustomNextRecurring</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fe86b57-93f5-4443-9eb2-6f91346dc316</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e27fe8d-5e2a-4fb7-8eb9-87463b824e06</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
